name: Test HELICS Install Action

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: gmlc-tdc/helics-action/install@main
      - name: Test running helics_broker
        run: |
          echo "PATH=$PATH"
          ls /c/Users/runneradmin/AppData/Local/gmlc-tdc/helics/bin
          helics_broker --version
